import { cookies } from 'next/headers';
import './global.css';
import StoreProvider from './StoreProvider';
import { Body, Header } from '@ui';
import { getInitialThemeValue } from '@utils';

export const metadata = {
  title: 'Welcome to demo2',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();

  return (
    <html>
      <StoreProvider theme={getInitialThemeValue(cookieStore)}>
        <Body>
          <Header />
          bububu
          {children}
        </Body>
      </StoreProvider>
    </html>
  );
}
